### ISSUE TITLE
Compilation on iPhone fails

### ISSUE THREAD

**Issue by z-mp** [stasel/WebRTC-iOS#1]
Many thanks for submitting your work to a large audience. It is certainly a big time saver for folks starting to look into the integration of webRTC in their iOS projects. 
Project successfully compiles and runs when target is simulator. However, when target is real device, e.g. iPhone, project does not successfully compile. Xcode throws 2 errors on lines 30 and 32 in file VideoViewController.swift.

Would you pls look into this issue?

**Comment by stasel** [comment]
Hi, thanks for the feedback!
There was a minor API change in WebRTC version 1.1.23621. I managed to fix the issue, and it should work fine now on devices as well

**Comment by z-mp** [comment]
Awesome! Thx!
