### ISSUE TITLE
defaultSignalingServerUrl 

### ISSUE THREAD

**Issue by harshkumarios** [stasel/WebRTC-iOS#102]
Hi team,
I am trying to run this demo. But the defaultSignalingServerUrl I could not find ,I tried to run node.js folder in my system.But I have no idea for backend. Terminal says npm command not found.

So , please guide me how can I run this demo and integrate into my code as well.
Thanks

**Comment by stasel** [comment]
Closing the issue due to inactivity, please feel free to reopen the issue if you still encounter problems
