### ISSUE TITLE
Remote video not rendering in video screen

### ISSUE THREAD

**Issue by derickito** [stasel/WebRTC-iOS#112]
Hi,

I got the app up and running with the signaling server and audio is working fine. I'm also able to see the camera locally on the respective device, but I can't see the remote video on either device. I saw a previous issue that said you have to start video before sending the offer/answer. I tried and it still didn't work.

Since the video screen is a modal, I also tried adding the offer and answer buttons in the video screen, so I can keep it open, but it still didn't work.

Thanks,

**Comment by derickito** [comment]
So after posting this issue I found this bug that was posted on a Google forum [https://bugs.chromium.org/p/webrtc/issues/detail?id=11727](https://bugs.chromium.org/p/webrtc/issues/detail?id=11727)
It seems the old precompiled libraries have been deprecated and no longer work. I'm not sure if this project uses the precompiled ones or if you compiled your own, but seems like that's the issue

**Comment by derickito** [comment]
I looked at the package dependencies and noticed that you're using your own compiled library, so it seems this is not the issue. Not sure what's wrong on my end then.

**Comment by derickito** [comment]
I found the problem. I was using 2 devices that are running iOS 16 Beta 3. I assumed that this wouldn't affect WebRTC, but apparently it does. I used a device running iOS 13 and another running iOS 16 Beta 3 and I was able to see the remote view in the iOS 16 Beta 3 device. So it seems the issue is the sending of the video, not the rendering of it.

Not sure if anyone else will run into this, but I'll leave this here, just in case.

**Comment by stasel** [comment]
Hey @derickito thanks for the heads up. Maybe there are some breaking changes on iOS 16 - worth testing

**Comment by derickito** [comment]
Yeah, hopefully they address it in the betas or the WebRTC team will fix it after iOS 16 is released. In the meantime I'm switching to developing in iOS 15 or lower.
I manually recompiled the WebRTC framework using Xcode 14 Beta 3, hoping it would make a difference, but I'm still getting the same issue.
I'll test again once iOS 16 is released and I'll keep an eye out for any mention of this in the WebRTC Google group.

Thanks again,

**Comment by derickito** [comment]
As of iOS 16 Beta 3 this is no longer an issue. Let's hope they don't break it again 🤞
