### ISSUE TITLE
peerConnection status stuck on "gathering" if I use 4g connection

### ISSUE THREAD

**Issue by jsyrtsov** [stasel/WebRTC-iOS#113]
Hello,

I really appreciate your work and it has helped me a lot studying WebRTC tech in iOS.

I understand that this problem is not connected with your demo App, problem is on WebRTC side, but I hope that you can give me some advice with troubleshooting.

If I try to make a call (send offer from one device + receive answer to that device) with Wi-Fi connection everything works fine, peer connection status changing stable -> checking -> gathering -> connected. (I attached screenshot with logs)

But if I try to make the same call with 4g connection on special provider peer connection statuses changing stable -> checking -> gathering. (I attached screenshot with logs) 

If I try to make the same call with 4g connection on different provider everything works fine. 

![image](https://user-images.githubusercontent.com/58340627/179223435-598c64da-3956-4f34-afad-dd729c20faec.png)
this is good situation

![image](https://user-images.githubusercontent.com/58340627/179223564-15ee8585-37fc-468d-9a40-ff9a56341d3f.png)
this is bad situation

**Comment by stasel** [comment]
Hi, sorry for the late response.
I'm happy that this demo project helped you learning about WebRTC :)

Unfortunately I'm not an expert on WebRTC myself but the reason can be that the device cannot reach the other device. If you are on 4g, you should use a TURN server to relay all network between devices in different networks (wifi <--> 4g)

**Comment by jsyrtsov** [comment]
@stasel I added turn server to config with url, username and credential and now I am able to call with 4g and wi-fi, thank you)
