### ISSUE TITLE
Does it support watchOS

### ISSUE THREAD

**Issue by 1garipdeveloper** [stasel/WebRTC-iOS#116]
I can't attach with CocoaPods. It also gives errors when I add it as a package.

Does WebRTC support watchOS?

**Comment by stasel** [comment]
Hello, this demo project supports only iOS.
Supporting WebRTC on WatchOS requires to recompile it and it may be not possible without modifications to the source code.

**Comment by 1garipdeveloper** [comment]
@stasel Thanks for your reply.

**Comment by raymondwelch33** [comment]
to piggyback off this -- I see a gap we could fill in the Open-source community @stasel - can we expand / evolve this library to utilize Google's `WebRTC` as the foundation -- but extend the current state to work on macOS (audio & video) & watchOS (audio only)?

**Comment by raymondwelch33** [comment]
As of `watchOS 9,` web sockets are NOT allowed (except for audio streaming apps) - per Apple's rules.
