### ISSUE TITLE
[Deprecated Package] swift-nio-zlib-support - Question + Fix Suggestion. 

### ISSUE THREAD

**Issue by raymondwelch33** [stasel/WebRTC-iOS#121]
Whilst inspecting this fine repository, I discovered a `Swift Package Manager` dependency on the package, `swift-nio-zlib-support` - mentioned above, and linked just below. 

**Repo:** (https://github.com/apple/swift-nio-zlib-support). 

I am creating this issue for two reasons. 

**1.** I do **NOT** understand why the demo app even has this dependency in the first place. So if you could answer that, that would be great. 

**2.**  Could you please fix this repository with the package and method Apple suggests to utilize in my statements below? 

It seems the package by Apple is deprecated and suggested to **NOT** be used to gain the functionality it previously enabled - in the repo's final commit, pushed around 15 months ago, it says to use the package via a new repo and has instructions on how to gain the same support / functionality from the package in that repo: https://github.com/apple/swift-nio-zlib-support/commit/cd3ad8e66fb389b80fd84b8b07561452d653e6f7

**New repo:**  https://github.com/apple/swift-nio-extras

**Comment by stasel** [comment]
Hi @raymondwelch33 thanks for reporting the issue.
The package was a dependency for the Starscream websocket package. 
Updating to the latest version of Starscream got rid of the dependency.

I hope it's fine now. Feel free to reopen the ticket if the issue still occurs

**Comment by raymondwelch33** [comment]
@stasel - Great! Thanks for updating the `Starscream` Dependency. 

I noticed you also updated the `StarscreamProvider` class, but I am a bit confused on why you made the changes you did. Specifically, why did you remove `WebSocketClient` ? 

**See image below:** 
<img width="1624" alt="StarscreamProvider - Removed WSC" src="https://user-images.githubusercontent.com/91862649/193452063-07f3f27a-2fe3-4e8c-87d4-562f7123917b.png">
