### ISSUE TITLE
Own Voice noice 

### ISSUE THREAD

**Issue by saroar** [stasel/WebRTC-iOS#14]
did you notice when we have a speaker on and video call one person listen to his own voice? i follow your code and my app is production but i have big voice issue don't know how to solve 

https://testflight.apple.com/join/QJN9cvrn

**Comment by saroar** [comment]
also like to ask you how we switch camera ?

**Comment by KeDaQHR** [comment]
This is my implementation of switching cameras:

func useFrontCamera() {
  guard let renderer = localVideoRenderer else { return }
  stopCaptureLocalVideo(renderer: renderer)
  startCaptureLocalVideo(renderer: renderer, cameraPoistion: .front)
}
	
func useBackCamera() {
  guard let renderer = localVideoRenderer else { return }
  stopCaptureLocalVideo(renderer: renderer)
  startCaptureLocalVideo(renderer: renderer, cameraPoistion: .back)
}

func stopCaptureLocalVideo(renderer: RTCVideoRenderer) {
  localVideoTrack?.remove(renderer)
  localVideoRenderer = nil
}

**Comment by saroar** [comment]
@KeDaQHR what is `localVideoRenderer`?

here is my var

```
class CallWebRTCC: NSObject {

    private var localRenderView: RTCEAGLVideoView?
    private var localView: UIView!
    
    private var remoteRenderView: RTCEAGLVideoView?
    private var remoteView: UIView!
    
    private var factory: RTCPeerConnectionFactory!
    private var peerConnection: RTCPeerConnection!
    private var localCandidates = [RTCIceCandidate]()
    
    private var videoCapturer: RTCVideoCapturer?
    private var remoteStream: RTCMediaStream?
    
    private var localAudioTrack: RTCAudioTrack!
    private var localVideoTrack: RTCVideoTrack!
```

**Comment by KeDaQHR** [comment]
@saroar I created this property to hold a reference to the local RTCVideoRenderer.

**Comment by stasel** [comment]
Hi @saroar 
I tested the app and couldn't hear my own voice when I'm on speaker. Are you far enough from the second device? because then the other device may hear you as well and cause this effect
