### ISSUE TITLE
 can I get  transcribe audio from  video call from caller 

### ISSUE THREAD

**Issue by EswarSatti** [stasel/WebRTC-iOS#143]
I need help related to  transcribe in video call  by peerConnection ,If call A to call B need to  transcribe audio of call A to call B screen vice versa in ios Platform

**Comment by EswarSatti** [comment]
in swift language

**Comment by stasel** [comment]
Hi, unfortunately, WebRTC does not provide transcription functionality. 
You will have to manually implement this by trying to come up a way to hook into WebRTC's audio or the standard AVAudioSession. Unfortunately I have never done this and cannot guide you further with the solution :(
