### ISSUE TITLE
Need to establish server in java. Please provide the setup.

### ISSUE THREAD

**Issue by BarjatyaAyushi** [stasel/WebRTC-iOS#149]

**Comment by stasel** [comment]
Hi @BarjatyaAyushi ,
Unfortunately I do not have any plans to provide additional signaling server implementations.
The goal of this repository is to be educational and give the visitors a good starting point implementing their own WebRTC solution. 
Please feel free to explore and learn the code to get familiar with the technology

**Comment by BarjatyaAyushi** [comment]
But we have working with Java. now used node js. any suggestion or direction?

**Comment by stasel** [comment]
I would suggest to research about signaling server and implement the ideas in Java
