### ISSUE TITLE
how use this code for calling many times

### ISSUE THREAD

**Issue by sashastg** [stasel/WebRTC-iOS#15]
Hello,
thanks for sharing this code!

i had checked everything and cant find way how i can call many times.
its looks like sends only 1 times  list of ice candidates.

for every new call  i need re-create webRTCClient ?

**Comment by stasel** [comment]
Hi there,
Yes, you are correct. The only way to reset everything is to relaunch the app on both devices. It is written in the Readme.md file. 

I may introduce a "reset" button in the future but I am not sure yet because I want this example to be as simple as possible.

**Comment by sashastg** [comment]
what you think if for every call i will create new class WebRTCClient ?
if there is method  "dispose" for WebRTCClient class ?

**Comment by stasel** [comment]
Yes this is an option. You can also make your WebRTCClient to re-create WebRTC's PeerConnectionClient instance every call as well
