### ISSUE TITLE
WebRTC with Wowza Signaling server.

### ISSUE THREAD

**Issue by bshashi10** [stasel/WebRTC-iOS#16]
Hello, 

Im trying to implement this code with wowza signaling server url, im not able to get remote SDP. can you please help me with that.

Thanks

**Comment by saroar** [comment]
I think becz of there API is this app send SDP are not same you have to check there API and know what they want from your IOS hope it will help
I am using my own signaling with swift back end can help you if want

**Comment by bshashi10** [comment]
Hi @saroar 
First of all thanks for your reply.

I would be really thankful  if you provide me some guidance so that I can overcome my problem that currently I'm facing

Let me provide you brief details about problem that I'm facing

Main objective is create a streaming based app that will behave like facetime and facebook messenger video calling feature

To achieve that i set up wowza streaming engine (Licensed based ) and webRTC on my test server
I wants to set up socket based connectivity and generate SDP URL that provide me real time connectivity

Here is the SDP URL: "wss://5c183e49b586e.streamlock.net/webrtc-session.json"

Using this SDP URL, I'm able to generate a demo on Android that is realtime steaming.

I followed following link for Android "https://github.com/AntonZorin/Android-wowza-webRtc-sample" and it's working grate. 

and I'm able to sync Android with web as well, but from IOS  I'am are unable to get any help, how to retrieve stream from SDP URL and how we can send stream using SDP URL from IOS device.

And we are not aware of Stun server can you please throw some light on that

If you provide me some guidance on that It will be really helpful.

Thanks.

**Comment by bshashi10** [comment]
Hi @saroar

Can you please assist me in this matter.

Thanks

**Comment by saroar** [comment]
@bshashi10 did you fixed your problem if not send me ur skype

**Comment by bshashi10** [comment]
i'm still stuck on the same issue. 

my Skype Id :- https://join.skype.com/invite/foCDHQdF6VqX

**Comment by stasel** [comment]
Hi guys I really appreciate the discussion here but I am closing this issue because it is not related to the repo. I can help with the example code but I couldn't advise any further.

**Comment by KT786** [comment]
Hello @saroar  and @bshashi10  I am facing the same issue so please provide me some guidance on how to fix them
