### ISSUE TITLE
LTE to WIFI connections not working for WebRTC

### ISSUE THREAD

**Issue by saroar** [stasel/WebRTC-iOS#18]
LTE to WIFI connections not working for WebRTC swift does not work i have your code on production app with my own turn server :( do you know why it's hot working?
my production app does not working :( 
appName is: AddaMe on `AppleStore`

**Comment by Sovenger** [comment]
LTE to WiFi works for me and I’m using a turn server. The issue is somewhere else. What have you tried to troubleshoot?

**Comment by SimonTheCat** [comment]
try to use TURN server

**Comment by neilyoung** [comment]
It’s definitely that: an issue with TURN


Sent from my iPhone

**Comment by saroar** [comment]
@Sovenger thanks for reply i use my own turn server 
```
public let defaultIceServers = [
    "stun:myserverip:3478",
    "stun:stun.l.google.com:19302",
    "stun:stun1.l.google.com:19302",
    "stun:stun2.l.google.com:19302",
    "stun:stun3.l.google.com:19302",
    "stun:stun4.l.google.com:19302",
    "stun:stun.services.mozilla.com"
]

public let iceServers = [
    RTCIceServer(
        urlStrings: ["turn:myserverip:3478?transport=udp"],
        username:    "username",
        credential:  "password"
    ),
    RTCIceServer(urlStrings: defaultIceServers)
]
``` is it looks good?
here is my docker i use https://github.com/saroar/AddaMe-TURN-server

do i need enable Certificates ?

**Comment by SimonTheCat** [comment]
work config
`listening-ip=1.1.1.1
relay-ip=1.1.1.1
realm=turn.yourdomain.com
fingerprint
lt-cred-mech
no-loopback-peers
no-multicast-peers
user=user:pass
cert=/etc/letsencrypt/live/yourdomain.com/fullchain.pem
pkey=/etc/letsencrypt/live/yourdomain.com/privkey.pem`
in code
`config.iceServers = [RTCIceServer(urlStrings: ["turn:turn.yourdomain.com:3478","turn:turn.yourdomain.com:5349"], username: "user", credential: "pass")]`

**Comment by saroar** [comment]
may i ask about this `1.1.1.1` why is 1.1.1.1 is it cloudfare DNS ip?

**Comment by saroar** [comment]
@SimonTheCat how do i check my server with my ios app ? so its working fine?

**Comment by saroar** [comment]
i try here everything was working? can i also try my production with turn server?

**Comment by SimonTheCat** [comment]
1.1.1.1 - its your server ip

**Comment by saroar** [comment]
can you please test this server is it will work turn:157.230.20.34:3478?transport=tcp user: alif password: password this is for test if it will work i will implement in my real server thanks @SimonTheCat

**Comment by saroar** [comment]
does anybody can help me is local everything is working with same turn server i try production not working :( @SimonTheCat can you help me live?

**Comment by saroar** [comment]
@SimonTheCat can you check please this is working on local I try with wifi + LTE but when I try from production server its does not working so can you check this my turn server thanks 

http://prntscr.com/nc2fyv

**Comment by saroar** [comment]
i am already 3 weeks stuck is anybody tries in production :( i try everything it does not work @stasel @neilyoung @Sovenger @SimonTheCat

**Comment by saroar** [comment]
its working on my local wifi ipad with LTE with mobile but when i push to production it does not work 
my turn server logs 
https://gist.github.com/saroar/a9382bd91b15c2c6fa1057b03eb8f659

**Comment by SimonTheCat** [comment]
check certificate

**Comment by saroar** [comment]
@SimonTheCat i don't have a certificate ok let me try

**Comment by saroar** [comment]
here is a new update 
iPad wifi to LTE iPhone 6 working 
but
LTE iPhone 6 to iPad wifi `not` working i try also paid turn server 

```[RTCIceServer(urlStrings: ["stun:eu-turn2.xirsys.com","turn:eu-turn2.xirsys.com:80?transport=udp","turn:eu-turn2.xirsys.com:3478?transport=udp","turn:eu-turn2.xirsys.com:80?transport=tcp","turn:eu-turn2.xirsys.com:3478?transport=tcp","turns:eu-turn2.xirsys.com:443?transport=tcp","turns:eu-turn2.xirsys.com:5349?transport=tcp"],
            username: "username fake ",
            credential: "password invalid"
            )]```

**Comment by SimonTheCat** [comment]
try to use only one turn server.

**Comment by saroar** [comment]
@SimonTheCat already try can you try my one turn server please here is it 
`turn:138.68.6.52:3478?transport=udp` username: alif, password: password 
i think problem in my code can you check my webRTC code please attach my last post thanks

**Comment by SimonTheCat** [comment]
Simon Cat#5498 text to me in diskord

**Comment by saroar** [comment]
Can’t find it :( alif #1970 may be u know how to find it I am also have on vapor server group

**Comment by yogirajh007** [comment]
@saroar How did you got it working finally?

**Comment by saroar** [comment]
@yes i did sorry for late reply it problem about ur stun, tun fixed it i hope it will work 
best of luck cant
