### ISSUE TITLE
GoogleWebRTC library conflict on IOS 12 to 13.3

### ISSUE THREAD

**Issue by SimonTheCat** [stasel/WebRTC-iOS#19]
GoogleWebRTC 
ios 12.2
`objc[287]: Class RTCCVPixelBuffer is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1c29eaf98) and /private/var/containers/Bundle/Application/3057B118-2044-4852-8672-13C9DF6DEC00/WebRTC-Demo.app/Frameworks/WebRTC.framework/WebRTC (0x101604a10). One of the two will be used. Which one is undefined.
objc[287]: Class RTCWrappedNativeVideoDecoder is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1c0863458) and /private/var/containers/Bundle/Application/3057B118-2044-4852-8672-13C9DF6DEC00/WebRTC-Demo.app/Frameworks/WebRTC.framework/WebRTC (0x101604a60). One of the two will be used. Which one is undefined.
objc[287]: Class RTCWrappedNativeVideoEncoder is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1c08634a8) and /private/var/containers/Bundle/Application/3057B118-2044-4852-8672-13C9DF6DEC00/WebRTC-Demo.app/Frameworks/WebRTC.framework/WebRTC (0x101604ab0). One of the two will be used. Which one is undefined.
objc[287]: Class RTCVideoDecoderVP8 is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1c08631b0) and /private/var/containers/Bundle/Application/3057B118-2044-4852-8672-13C9DF6DEC00/WebRTC-Demo.app/Frameworks/WebRTC.framework/WebRTC (0x101604b28). One of the two will be used. Which one is undefined.
`

**Comment by SimonTheCat** [comment]
https://bugs.chromium.org/p/webrtc/issues/detail?id=10560

**Comment by stasel** [comment]
Oh wow, looks like Google WebRTC framework conflicts with some Apple's Safari WebRTC classes.
Thanks for the report. Lets hope they will fix it soon :)

**Comment by neilyoung** [comment]
Seeing this too but I cannot see any negative impact at runtime

**Comment by SimonTheCat** [comment]
so, it fixed in 12.3 beta.
I temporary build it from source with rename.  Waiting for release ios 12.3.

**Comment by stasel** [comment]
Cool! Thanks again for the heads up!

**Comment by iStorry** [comment]
@SimonTheCat can you please explain how did you solve this issue. Thank you

**Comment by SimonTheCat** [comment]
@iStorry copy sources with this https://webrtc.org/native-code/ios/  instructions and before you compile that, you have to rename the conflicting functions

**Comment by SimonTheCat** [comment]
apple not solve the problem in release IOS 12.3

**Comment by saroar** [comment]
@SimonTheCat did you send an email about this bug?

**Comment by jijile** [comment]
How should this problem be solved?

**Comment by jijile** [comment]
How should this problem be solved? @SimonTheCat

**Comment by iStorry** [comment]
@jijile 
Check this out

> @iStorry copy sources with this https://webrtc.org/native-code/ios/ instructions and before you compile that, you have to rename the conflicting functions

**Comment by stasel** [comment]
Unfortunately this still exists in iOS 13 GM seed
However only 1 class conflicts:

```
bjc[1577]: Class RTCCVPixelBuffer is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1d9081410) and /private/var/containers/Bundle/Application/C5EB8E01-9484-4081-AE20-CCDBC0AF753F/WebRTC-Demo.app/Frameworks/WebRTC.framework/WebRTC (0x1050575a0). One of the two will be used. Which one is undefined.
```

**Comment by fukemy** [comment]
so bad, i got error in ios 13.3, iphone XR

**Comment by fukemy** [comment]
it's take my app CRASHHHHHHHHHHH

> @iStorry copy sources with this https://webrtc.org/native-code/ios/ instructions and before you compile that, you have to rename the conflicting functions

Hi @SimonTheCat , it saw this website but it's really hard to change class name, can you help by provide step by step, thanks u so much

**Comment by grago** [comment]
I'm building a WebRTC app right now and i'm getting this warning. It would be really bad if this causes random crashes :/

**Comment by SimonTheCat** [comment]
Temporary solution(use at your own risk):
1. make work dir
```
mkdir build_rtc
```
```
cd build_rtc
```
2. Install the Chromium depot tools
```
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
```
```
export PATH=`pwd`/depot_tools:"$PATH"
```
3. Download webrtc sources
```
fetch --nohooks webrtc_ios
```
```
ls

depot_tools src

cd src
```
4. Check and select branches(optional. May skip this step, if you use master branch)
4.1 Check branches
```
git branch -a

...
remotes/branch-heads/...
  remotes/branch-heads/m73
  remotes/branch-heads/m74
  remotes/branch-heads/m75
  remotes/branch-heads/m76
  remotes/branch-heads/m77
  remotes/branch-heads/m78
  remotes/branch-heads/m79
  remotes/branch-heads/phoglund-test
  remotes/origin/HEAD -> origin/master
  remotes/origin/infra/config
  remotes/origin/lkgr
  remotes/origin/master

```
4.2 checkout
```
git checkout remotes/branch-heads/m79
```
5. sync
```
gclient sync
```
6. create new local branch
```
git new-branch local_dev_fix_webrtc
```
7. Find and replace "RTCCVPixelBuffer" with some prefix in sources
```
grep -rl --include=\*.{gn,h,m,mm} "RTCCVPixelBuffer" . | xargs sed -i .bak -e 's/RTCCVPixelBuffer/APPLE_MUST_FIX_IT_RTCCVPixelBuffer/g'
```
8. Rename some files
```
mv ./sdk/objc/Framework/Headers/WebRTC/RTCCVPixelBuffer.h ./sdk/objc/Framework/Headers/WebRTC/APPLE_MUST_FIX_IT_RTCCVPixelBuffer.h
mv ./sdk/objc/components/video_frame_buffer/RTCCVPixelBuffer.h ./sdk/objc/components/video_frame_buffer/APPLE_MUST_FIX_IT_RTCCVPixelBuffer.h
mv ./sdk/objc/components/video_frame_buffer/RTCCVPixelBuffer.mm ./sdk/objc/components/video_frame_buffer/APPLE_MUST_FIX_IT_RTCCVPixelBuffer.mm
```
9. Generating project files(arm,arm64,x64 for simulator)
```
gn gen out/ios_arm --args='target_os="ios" target_cpu="arm" is_debug=false ios_enable_code_signing=false'
gn gen out/ios_arm64 --args='target_os="ios" target_cpu="arm64" is_debug=false ios_enable_code_signing=false'
gn gen out/ios_sim --args='target_os="ios" target_cpu="x64" is_debug=false ios_enable_code_signing=false'
```
or debug version(is_debug=true)
```
gn gen out/ios_arm --args='target_os="ios" target_cpu="arm" is_debug=true ios_enable_code_signing=false'
gn gen out/ios_arm64 --args='target_os="ios" target_cpu="arm64" is_debug=true ios_enable_code_signing=false'
gn gen out/ios_sim --args='target_os="ios" target_cpu="x64" is_debug=true ios_enable_code_signing=false'
```
10. Compiling with ninja
```
ninja -C out/ios_arm framework_objc
ninja -C out/ios_arm64 framework_objc
ninja -C out/ios_sim framework_objc
```
11. Join all in one "fat" framework
```
mkdir out/ios
cp -R out/ios_arm64/WebRTC.framework/ out/ios/WebRTC.framework
lipo -create out/ios_arm/WebRTC.framework/WebRTC out/ios_arm64/WebRTC.framework/WebRTC out/ios_sim/WebRTC.framework/WebRTC -output out/ios/WebRTC.framework/WebRTC
```
12. Done! resault: out/ios/WebRTC.framework 
You may create private cocoapod repo and use as pod 'GoogleWebRTC', :git => 'your github repo'

Ref:
https://webrtc.googlesource.com/src/+/refs/heads/master/docs/native-code/ios/index.md

**Comment by SimonTheCat** [comment]
GoogleWebRTC prebild binary(use at your own risk)

[GoogleWebRTC_master_release20200129.zip](https://github.com/stasel/WebRTC-iOS/files/4127014/GoogleWebRTC_master_release20200129.zip)

**Comment by fukemy** [comment]
i love u @SimonTheCat

**Comment by SimonTheCat** [comment]
Good news. Xcode 11.4 beta 3 has no problem. But! I hope in the release version, this will completely be fixed(i know issue: beta - no problem, release - problem has present).

**Comment by Isuru-Nanayakkara** [comment]
> Good news. Xcode 11.4 beta 3 has no problem. But! I hope in the release version, this will completely be fixed(i know issue: beta - no problem, release - problem has present).

I'm still getting this in Xcode 11.4 beta 3 😕

**Comment by SimonTheCat** [comment]
@Isuru-Nanayakkara  maybe clean install Xcode 11.4?

**Comment by SimonTheCat** [comment]
Xcode  11.4 release version has no this issue!! Congratulations!!

**Comment by SimonTheCat** [comment]
Xcode 11.4  IOS 13.x has no this issue!! Congratulations!!
Xcode 11.4  IOS 12.x getting this issue((

**Comment by SimonTheCat** [comment]
i recommend build library from source

**Comment by Isuru-Nanayakkara** [comment]
> @Isuru-Nanayakkara maybe clean install Xcode 11.4?

I was previously using Xcode 11.4 beta 3. I just installed the stable Xcode 11.4 and ran it in my iPhone running the latest iOS version 13.4. Then I didn't get this error. However I ran the same project on my iPad which had the old iOS version and I still got the error. It disappeared after updating it to the latest iOS version as well.

**Comment by ashwinau** [comment]
Hai I'm new to WebRTC, and I want to know if there are  any options to display the connected devices from singling server to our project so that we can send offers to particular device or selected device.?

**Comment by SimonTheCat** [comment]
@stasel have you tetsed GoogleWebRTC 1.1.31999?

**Comment by stasel** [comment]
> @stasel have you tetsed GoogleWebRTC 1.1.31999?

Yes, I tested 1.1.31999 with iOS 14 and iPad OS 14 and it works fine except one very strange issue on iOS 14 when tapping on "video" before WebRTC connection

**Comment by stasel** [comment]
Looks like the issue has been fixed on WebRTC side as well. Closing the issue.
