### ISSUE TITLE
Type 'SignalClient' does not conform to protocol 'WebSocketDelegate'

### ISSUE THREAD

**Issue by Ivan411** [stasel/WebRTC-iOS#2]
Hi! I load your project and made something for my server. When I copy/past files WebRTCClient, WebRTC-Bridging-Header, SignalClient, RTCStates, RTCSessionDescription+JSON, RTCIceCandidate+JSON to my project. I have some problems - in SignalClient file 
"Type 'SignalClient' does not conform to protocol 'WebSocketDelegate'"
http://joxi.ru/BA0Leg0HJw1zXA
Xcode want to add only 
 func websocketDidReceiveData(socket: WebSocketClient, data: Data)
But all protocol methods are implemented.
Can you help me please?

**Comment by stasel** [comment]
Hi, Which version of Starscream are you using? I tested my code and it looks fine with Starscream 3.0.5. Can you try to re-test?

**Comment by Ivan411** [comment]
I comment func websocketDidReceiveData(socket: WebSocketClient, data: Data)
 in WebSocketDelegate. your project work normal. is this important func?

**Comment by stasel** [comment]
I don't use `websocketDidReceiveData` in my demo so you can safely comment it out
By the way, which version of Xcode are you using?

**Comment by stasel** [comment]
I tested it and I don't get any crash when I don't give permission to use the microphone. I'm sorry but as this project is a demo project it may not be covering all the edge cases properly. I suggest to get support from WebRTC library or Apple forums depending on the crash location.
