### ISSUE TITLE
After Turn on Video can't turn off 

### ISSUE THREAD

**Issue by saroar** [stasel/WebRTC-iOS#21]
After the open video, it can't turn off
if one of user click back and he can't see his self video but other use still see his video so we have to remove the video from live after one of user click back/turn off video

**Comment by saroar** [comment]
in WebRTC class i this this function but no luck 
```
func removeVideo() {
        for transceiver in self.peerConnection.transceivers {
            if transceiver.mediaType == .video {
                transceiver.stop()
            }
        }
    }
```
i try this but it stop video but wheni come back video it does not work :(

**Comment by stasel** [comment]
Hi @saroar, In my demo I didn't put effort to do more advance functionalities such as turning on/off video.

in your example you can also try to stop capture in your video capture clas s

**Comment by saroar** [comment]
@stasel it does not work let me try if i can do it or if you know how to do it you can share with us thanks

**Comment by saroar** [comment]
fixed it thanks :) if you will have time I can create pull request

**Comment by mrfarukturgut** [comment]
@saroar wish, you have shared your solution man

**Comment by mrfarukturgut** [comment]
`  func pauseVideo() {
        self.setVideoEnabled(false)
    }
    
    func unpauseVideo() {
        self.setVideoEnabled(true)
    }`

```
     private func setVideoEnabled(_ isEnabled: Bool) {
        let videoTracks = self.peerConnection.transceivers.compactMap { return $0.sender.track as? RTCVideoTrack }
        videoTracks.forEach { $0.isEnabled = isEnabled }
    }
```

**Comment by saroar** [comment]
@mrfarukturgut sure i will share with you here
