### ISSUE TITLE
credentials for turn server

### ISSUE THREAD

**Issue by sashastg** [stasel/WebRTC-iOS#22]
Hello,
thanks for your work.

i got a problem.
when using TURN server its require  credential/password.

can you help me, how i can use  credential/password  for turn server with current code.
something like this:
https://stackoverflow.com/questions/25446266/turn-and-stun-server-credentials

many thanks

**Comment by SimonTheCat** [comment]
`config.iceServers = [RTCIceServer(urlStrings: ["turn:turn.yourdomain.com:3478","turn:turn.yourdomain.com:5349"], username: "user", credential: "pass")]`

**Comment by sashastg** [comment]
thanks!!!!!

**Comment by stasel** [comment]
Thats for the quick response @SimonTheCat

I’m closing this issue. Feel free to reopen the issue if you are still having problems.

**Comment by hishammir** [comment]
@SimonTheCat from a security point of view, what can go wrong if these credentials fall into wrong hands?
