### ISSUE TITLE
remote sdp doesn't receive

### ISSUE THREAD

**Issue by ERYURTTAS** [stasel/WebRTC-iOS#23]
Hello, I downloaded and installed your project to my devices. Also I builded up my signaling server and its working on a remote nodejs server, ssl certificates are ok and I have 'wss' connection (I changed defaultsignallingserver in config.swift file as : wss://xxxxxx.com:8484), everything looks ok, device status are connected, when I click 'send offer' button: on the device that I clicked to button 'local sdp' is count up and I see offer and sdp datas on terminal of my server as broadcast data  but nothing happening on other device. I tried both of devices but result is same. Can you help me to solve this problem?

Thank you for your works.

**Comment by stasel** [comment]
Thats interesting. I havn't tested my code with secure web sockets protocol.
Can you share your signaling server code?

**Comment by ERYURTTAS** [comment]
thank you for your response, here is my signaling code:

`const HTTPS_PORT = process.env.PORT || 8484;
const HTTPS_IP = '0.0.0.0';

const fs = require('fs');
const https = require('https');
const WebSocket = require('ws');
const WebSocketServer = WebSocket.Server;

const serverConfig = {
  **key: fs.readFileSync('SSLKEY.key'),
  cert: fs.readFileSync('SSLCRT.crt'),**
};

const handleRequest = function(request, response) {
  console.log('request received -- : ' + request.url);
  if (request.url === '/'){
    console.log("request handled index.html");
    response.writeHead(200, {'Content-Type': 'text/html'});
    response.end(fs.readFileSync('index.html'));
  }
  if (request.url === '/webrtc.js'){
    console.log("request handled webrtc.js");
    response.writeHead(200, {'Content-Type': 'application/javascript'});
    response.end(fs.readFileSync('webrtc.js'));
  }
};

const httpsServer = https.createServer(serverConfig, handleRequest);
httpsServer.listen(HTTPS_PORT,  () => {
  console.log("Server running at https://"+HTTPS_IP+":"+HTTPS_PORT+"/");
});

const wss = new WebSocketServer({server: httpsServer});

// Broadcast to all. ORIGINAL CODE
var c=0;
wss.broadcast = (ws, data) => {
    wss.clients.forEach((client) => {
        if (client !== ws && client.readyState === WebSocket.OPEN) {
            client.send(data);
        }
    });
};

wss.on('connection', (ws) => {
    console.log(`Client connected. Total connected clients: ${wss.clients.size}`)
    
    ws.onmessage = (message) => {
        console.log("broadcast message.data: %s",message.data + "\n");
        wss.broadcast(ws, String(message.data));
    }

    ws.onclose = () => {
        console.log(`Client disconnected. Total connected clients: ${wss.clients.size}`)
    }
});
`

**actually I want to use WebRTC chrome->iOS and chrome->Android**

I will deploy your exact code too and will inform you about result.

thank you.

**Comment by neilyoung** [comment]
From my experience there is no problem with @stasel’s code and secure ws

**Comment by ERYURTTAS** [comment]
Hello again, I solved the problem here is the solution:
My webrtc.js receives and sends sdp and candidates on browser over wss to app but in app 'websocketDidReceiveMessage' fires instead of 'websocketDidReceiveData' I think I send sdp and candidates as text or my server broadcast them as text I don't know. And I don't know how to send them as 'data'?(May be you can help me here)
I convert string message to data and wrote same codes to 'websocketDidReceiveMessage' from 'websocketDidReceiveData' and it works. May be converting string to data will be cause performance loss.
in SignalingClient.swift: 
```
    func websocketDidReceiveData(socket: WebSocketClient, data: Data) {
        print("received data: \(data)")
        let message: Message
        do {
            message = try self.decoder.decode(Message.self, from: data)
        }
        catch {
            debugPrint("Warning: Could not decode incoming message: \(error)")
            return
        }
        
        switch message {
        case .candidate(let iceCandidate):
            self.delegate?.signalClient(self, didReceiveCandidate: iceCandidate.rtcIceCandidate)
        case .sdp(let sessionDescription):
            self.delegate?.signalClient(self, didReceiveRemoteSdp: sessionDescription.rtcSessionDescription)
        }
    }
    
    func websocketDidReceiveMessage(socket: WebSocketClient, text: String) {
        let message: Message
        let data = Data(text.utf8) //**I just added this line**
        do {
            message = try self.decoder.decode(Message.self, from: data)
        }
        catch {
            debugPrint("Warning: Could not decode incoming message: \(error)")
            return
        }
        
        switch message {
        case .candidate(let iceCandidate):
            self.delegate?.signalClient(self, didReceiveCandidate: iceCandidate.rtcIceCandidate)
        case .sdp(let sessionDescription):
            self.delegate?.signalClient(self, didReceiveRemoteSdp: sessionDescription.rtcSessionDescription)
        }
    }
```

Thank you for your help.

**Comment by stasel** [comment]
I think I found the issue, in the signaling server code you have the following line:

```wss.broadcast(ws, String(message.data));```

If your remove the string casting and change it to:
```wss.broadcast(ws, message.data);```

It will broadcast the message as data and not as string

**Comment by ERYURTTAS** [comment]
yes, it's working, thank you for your helps.

**Comment by stasel** [comment]
Great! I'm closing the issue.
Feel free to reopen it if you have any further problems
