### ISSUE TITLE
how can I send data using emit function and how to receive the data using the  socket.on ack is there a way to send data and receive using webRTC-iOS please reply

### ISSUE THREAD

**Issue by ShaikBaji1911** [stasel/WebRTC-iOS#26]

**Comment by stasel** [comment]
Hello @ShaikBaji1911 
Please edit the issue: Add a description and make the title shorter.
As for your question I am not entirely understand what is the issue. I'll try to answer:

> how can I send data using emit function

What `emit` function do you mean? There is no `emit` function in the code base  

> how to receive the data using the socket.on ack

Information about the socket library used in the project can be found [here](https://github.com/daltoniam/Starscream)

> is there a way to send data and receive using webRTC-iOS

Yes, it's called data channels and is demonstrated in this project

**Comment by ShaikBaji1911** [comment]
I am asking can we send data and receive data after connecting to socket ?

**Comment by stasel** [comment]
Please look at the code and Starscream documentation for more details

**Comment by ShaikBaji1911** [comment]
I haven't found any function for passing the data and receiving the data can you please help me how to send data and retrieve after connecting to the socket I think in webSocket we can't able to send data but using socket.io library we can send I guess

**Comment by stasel** [comment]
To receive data, implement `websocketDidReceiveData` on your `WebSocketDelegate`.
To Send data, use `write` method on your `WebSocket` instance.

Since this issue is not related directly to the WebRTC demo app, It has been closed.
If you have any further question about how to use websockets, please try asking them in Starscream github repo.
