### ISSUE TITLE
a blank page is seen when tapping on video on iOS 13 beta 8

### ISSUE THREAD

**Issue by flyinglionSJ** [stasel/WebRTC-iOS#27]
Hi,

when I tried the video call, I got a blank page on ios 13 beta 8
![FL-02-09-2019-05-26-25 JPG](https://user-images.githubusercontent.com/54824252/64137125-211a8a80-cdab-11e9-8d74-12ea58356458.png)

**Comment by stasel** [comment]
Hi,
Did you build the project from master or xcode-11 branch?

**Comment by flyinglionSJ** [comment]
Hi Stasel,
I built from xcode 11 sample.

Best regards,
T

**Comment by flyinglionSJ** [comment]
By the way, Thank you so much for your work!  I’be been waiting for this for years

**Comment by stasel** [comment]
To be honest I didn't manage to test iOS 13 beta on a real device yet, only simulator which doesn't show video anyways.

Are you sure you used [xcode-11 branch](https://github.com/stasel/WebRTC-iOS/tree/xcode-11)? According to your screenshot it looks like you are building from master branch because on [xcode-11 branch](https://github.com/stasel/WebRTC-iOS/tree/xcode-11) the video view should be full screen

**Comment by flyinglionSJ** [comment]
Hi Stasel,

you are correct. That screen shot was from master. However, the same issue happened on xcode-11 folder also.

Thanks,
T

**Comment by flyinglionSJ** [comment]
Hi Stasel,

How are you doing?  I noticed that the video from video call eould be paused when the app in the bacground. Is it possible that the video is not paused when the app in the bacground state?

Thank you very much!

Best regards,
T

**Comment by flyinglionSJ** [comment]
Hi Stasel,

Please help so video is not paused when the app is in the background.

Thank you very much!

Best regards, 
T

**Comment by stasel** [comment]
Hi,
Video will always be paused when the app is not in foreground. This is a restriction from Apple. See [here](https://developer.apple.com/documentation/avfoundation/avcapturesession/interruptionreason/videodevicenotavailableinbackground)

**Comment by stasel** [comment]
By the way, did you manage to fix the issue above on iOS 13?
I don't have iOS 13 devices yet. I plan to test it next week or week after

**Comment by flyinglionSJ** [comment]
Hi Stasel,

I did not know how to fix it yet.  Would you please help to fix it?

Thank you very much Stasel!!!!

Best regards,
T

**Comment by stasel** [comment]
I’ll install the GM beta and try to teat this. Hopefully it’ll be out today

**Comment by flyinglionSJ** [comment]
Great thanks Stasel!

**Comment by stasel** [comment]
Hi, can you please retest?
I had video working properly with the following setup:

- iPhone X with iOS 13 GM Seed
- Xcode 11 GM Seed

Make sure to install latest pod dependencies as well (run `pod update`)

**Comment by flyinglionSJ** [comment]
Thank you so
much Stasel!  I retested it and the video issue was fixed.  However, the video on ios 13.1 beta did not show as full screen

**Comment by stasel** [comment]
Hi
This issue has been closed due to inactivity. Please feel free to reopen it if you still experiencing issues.
