### ISSUE TITLE
Offer is not getting at receiver side

### ISSUE THREAD

**Issue by shivamsharma-1996** [stasel/WebRTC-iOS#28]
Hye stasel,
hope you are well. I've cloned this repo. I'm creating an Offer from initiator  but not getting at other end. Can you please tell me is that problem related to your socket connection u're using???

**Comment by stasel** [comment]
Is the signaling server running? 
Both clients should show “connected” for their signaling status

**Comment by shivamsharma-1996** [comment]
No signalling status is showing "not connected".
What's the issue? I found your code best written in swift so cloned. Want it to run successfully .
please help me

**Comment by stasel** [comment]
The clients are not connected to the websocket server. 
Did you follow the instructions in the README file?
You need to change ‘config.swift’ and change the IP address to your signaling server.

**Comment by shivamsharma-1996** [comment]
No i couldn't understand.
I have to put my own signalling server in your code?

**Comment by shivamsharma-1996** [comment]
If you have any fully functional code . Can you give me that please?

**Comment by ShaikBaji1911** [comment]
is your server url is correct, check once your server side url hope it works

**Comment by shivamsharma-1996** [comment]
@ShaikBaji1911 @stasel  hye guyz, should I serve your script on server ?

**Comment by ShaikBaji1911** [comment]
@shivamsharma may I know how you are sending  and receiving sdp offer to remote candidate ? can you post the code or total class

**Comment by stasel** [comment]
Hi @ShaikBaji1911 
Please follow the instructions in the readme file. If anything is not clear in the readme feel free to ask here

**Comment by stasel** [comment]
Hi
This issue has been closed due to inactivity. Please feel free to reopen it if you still experiencing issues.
