### ISSUE TITLE
send data through webRTC 

### ISSUE THREAD

**Issue by ShaikBaji1911** [stasel/WebRTC-iOS#29]
how to send data through webRTC is there any function to send data ?

**Comment by shivamsharma-1996** [comment]
@ShaikBaji1911  can we connect on somewhere?
I felt we're on sam boat.

**Comment by shivamsharma-1996** [comment]
@ShaikBaji1911 I'm trying to put different signalling server what I've used inside my android app also.

**Comment by ShaikBaji1911** [comment]
ping me your email id I will connect you there @shivamsharma-1996

**Comment by shivamsharma-1996** [comment]
shivamsharma707@yahoo.com

**Comment by shivamsharma-1996** [comment]
shivamsharma707@yahoo.com

**Comment by ShaikBaji1911** [comment]
please reply @shivamsharma-1996  I have mailed you

**Comment by stasel** [comment]
Data channel example is available in this demo
