### ISSUE TITLE
Features Request PushKit + CallKit

### ISSUE THREAD

**Issue by saroar** [stasel/WebRTC-iOS#30]
Can you make this app with PushKit? when app is close :) other people can get call :)

**Comment by z-mp** [comment]
I think the intent behind this project is get you up to speed and upgrade to prod version on your own. CallKit and PushKit integration is absolute must, if you want to transition from "hobby" project to AppStore. My very early stage company - RelayServices.Cloud - is about to offer WebRTC iOS SDK with CallKit and PushKit integrated for FREE to help you accelerate your dev cycles. We are not  yet "live", but feel free to follow us on Instagram ([_relayservicescloud_](https://www.instagram.com/_relayservicescloud_/)) or Twitter ([@relayservicesc1](https://twitter.com/relayservicesc1)) to stay tuned.

**Comment by saroar** [comment]
@z-mp CHECK THIS OUT I HAVE HAVE IT MY OWN https://addaa.me
https://apps.apple.com/us/app/addaa/id1398824560
I DONE MY OWN CODE BUT I CAN'T SAY I DONT GREAT JOB BUT SO THAT'S WHY I AS ASK HIM TO DONE FOR EVERYONE :) BUT THANKS FOR YOUR REPLY

**Comment by stasel** [comment]
Thanks for the suggestion!
I was thinking on doing this but I decided it is out of scope for this repo. I tried to make the code as minimal as possible to avoid confusion and focus only in the WebRTC part.

Maybe in the future I'll create a more detailed example with pushKit and callKit

**Comment by saroar** [comment]
HIi have to with PushKit and CallKit but it not stable would you like to help me refactor code I can pay for that please email me saroar9@gmail.com let me know when you email me so I can remove my this or u can remove this post with my email thanks
