### ISSUE TITLE
Video problems at ios13

### ISSUE THREAD

**Issue by n1kron** [stasel/WebRTC-iOS#32]
Hi! 
After migration my app to iOS13, my videoCalls just disappear. Sound is ok, localView and remoteView is just white. At iOS12 everything is fine. Like this problem: https://github.com/stasel/WebRTC-iOS/issues/27
What did you change for demo?

**Comment by stasel** [comment]
Hey, can you test from ”xcode-11” branch?

**Comment by n1kron** [comment]
> Hey, can you test from ”xcode-11” branch?

I tested your demo from ”xcode-11” branch and it works perfectly. I just wanna know why this is happening and how did you fixed that :)

**Comment by stasel** [comment]
Yeah thats a super strange bug on iOS 13. No clue what caused it. Maybe the sdk version solved it.

Since xcode 11 is now released i plan to merge xcode-11 to master soon

**Comment by ERYURTTAS** [comment]
Hello, change your pod to (pod 'GoogleWebRTC', '~> 1.1') or directly (pod 'GoogleWebRTC', '1.1.29229') and update your pod with this command 'pod update' and after this command 'pod install' I tried yet a few hours ago on iPhone X, iphone7 plus it is working I saw video from android device to iPhone, but no sound output on iPhones. May be you can help me about sound output.
