### ISSUE TITLE
The file couldn’t be opened.

### ISSUE THREAD

**Issue by samuelail** [stasel/WebRTC-iOS#33]
When trying to open the demo project, this error " The file couldn’t be opened. " pops up. The only project that opens up is the swift signaling server.  Any help? or is this just an issue with the recent commit?

**Comment by stasel** [comment]
Hi @samuelail 
Project should be buildable without any issues. Did you follow the instructions in the readme?
What XCode version did you use?

**Comment by samuelail** [comment]
I used Xcode 11 . I tried It on 10.3 and It opened fine .  Possible compatibility issue?

**Comment by stasel** [comment]
This is strange, I cloned latest master to a clean directory and it worked for me (XCode 11.0). Did you run `pod install` and opened the `xcworkspace` file?

**Comment by samuelail** [comment]
Yes I did. It showed the swift signaling server which opened but nothing else opened.

**Comment by stasel** [comment]
Can you share your cocoapods and xcode versions?

Try also to remove the directory and clone latest master.

**Comment by stasel** [comment]
This issue has been closed due to inactivity. Please feel free to reopen it if you still experiencing issues.
