### ISSUE TITLE
Group audio or video calling supported ?

### ISSUE THREAD

**Issue by shivangpandya9** [stasel/WebRTC-iOS#34]
Hello ,

I check to connected with three device with code. Connection is successful but while offer call I can't give answer with two device. 
I have to cut call with one device to send answer with other device. 

Is group-calling possible with this code ? 
Thanks.

**Comment by stasel** [comment]
Hi @shivangpandya9 
Group calls is more advance topic and is not covered in this Demo. You should always use only 2 devices when running the demo project.
