### ISSUE TITLE
Connection f

### ISSUE THREAD

**Issue by niksard** [stasel/WebRTC-iOS#35]

**Comment by niksard** [comment]
Ice candidates comes before remote sdp was setting up. Fix:

func set(remoteSdp: RTCSessionDescription, completion: @escaping (Error?) -> ()) {
		self.peerConnection.setRemoteDescription(remoteSdp, completionHandler: { [weak self] (error) in
			self?.handlerRemoteDescriptionSet()
			completion(error)
		})
    }
    
    func set(remoteCandidate: RTCIceCandidate) {
		if self.peerConnection.remoteDescription != nil {
			self.peerConnection.add(remoteCandidate)
		} else {
			self.remoteCandidates.append(remoteCandidate)
		}
    }

	func handlerRemoteDescriptionSet() {
		self.remoteCandidates.forEach { self.peerConnection.add($0) }
	}

**Comment by stasel** [comment]
Hello, thank you for reporting the issue. Please edit the issue and make it more readable:

1. Provide a good title
2. Add the issue in the first message (you can edit it)
3. Please format your code correctly

**Comment by stasel** [comment]
This issue has been closed due to inactivity. Please feel free to reopen it if you still experiencing issues.
