### ISSUE TITLE
Identifying online users in WebRTC

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [stasel/WebRTC-iOS#36]
Hi 👋🏼 Thanks for putting together this project. It's really helpful.

I have a question. Is there a way to do something like getting a list of users connected to the server? I want to implement a feature like showing a list of online users.

Is there a way to do that through websockets itself?

**Comment by stasel** [comment]
Hi, happy that you find my project helpful.

Yes, you can implement online user list in your socket server. Your server tracks all open socket connections. Add a functionality to query the socket server about all online users and it should be great.

**Comment by stasel** [comment]
This issue has been closed due to inactivity. Please feel free to reopen it if you still experiencing issues.

**Comment by Isuru-Nanayakkara** [comment]
Sorry, I must have missed the notification email for your previous reply! Thanks for the response. I'll look into implementing it. Thank you :)
