### ISSUE TITLE
Speaker does not work

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [stasel/WebRTC-iOS#39]
Hi again,

I came across an issue with the speaker. Even though I have turned it on from the app (device is not muted and volume is turned all the way up), sound still does not come from the loud speaker of the device. It still comes from the receiver so I have to listen to it like I'm taking a normal phone call.

I tested this on an iPhone 6 and in an iPhone 11 Pro. This only occurs in iPhone 11 Pro. Any idea why this is happening?

**Comment by stasel** [comment]
Interesting, I don't own iPhone 11 pro to test. Can you share the iOS version on the devices?
Is there any error in the console? Maybe something related to AVSession?

**Comment by Isuru-Nanayakkara** [comment]
The iPhone 6 has iOS 12.4.3 and the iPhone 11 Pro has iOS 13.3.

No error messages or anything related to AVFoundation/AVSession in the console either.

**Comment by stasel** [comment]
Strange, I tried it on iPhone X running iOS 13.3 and speaker button works as expected.
Maybe try to run `pod update` to update WebRTC lib?

**Comment by stasel** [comment]
This issue has been closed due to inactivity. Please feel free to reopen it if you still experiencing issues.
