### ISSUE TITLE
pod install not respond

### ISSUE THREAD

**Issue by knottovt** [stasel/WebRTC-iOS#41]
Analyzing dependencies
Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`
.....

there 're freeze on this step
pls help me, many thank

**Comment by stasel** [comment]
Hi @knottovt 
This looks like a Cocoapods prodblem and not related to the WebRTC demo app. 

Try to contact Cocoapods team to get any help resolving your issue. 

Thanks!
