### ISSUE TITLE
Why it has no remote video view?

### ISSUE THREAD

**Issue by sean19870414** [stasel/WebRTC-iOS#42]
When I connected to both devices everything is working well, but video only has local view, how do I add remote view?

**Comment by stasel** [comment]
Hey @sean19870414 
Sorry for the late reply.
Make sure to tap on the "video" button on both devices. The video capture will start only when you hit the "video" button.

Are you still experiencing issues?

**Comment by amarantedaniel** [comment]
Hi, do both devices need to have video?

I'm trying it here with my phone and my emulator, and I can see my local video on my phone, but I can't see on on the emulator.

Audio works fine though.

**Comment by amarantedaniel** [comment]
> Hey @sean19870414
> Sorry for the late reply.
> Make sure to tap on the "video" button on both devices. The video capture will start only when you hit the "video" button.
> 
> Are you still experiencing issues?

Do you know why both devices need video for video to work?

I was trying it out using my phone and my simulator and I couldn't see the remote video from my phone on the simulator. It only worked when both devices supported video.

**Comment by stasel** [comment]
I also had issues displaying a video on a simulator. I suggest to use 2 physical devices to test video

**Comment by stasel** [comment]
This issue has been closed due to inactivity. Please feel free to reopen it if you still experiencing issues.
