### ISSUE TITLE
Changing volume for different participants

### ISSUE THREAD

**Issue by marvinkennis** [stasel/WebRTC-iOS#47]
Thank you so much for getting this together. Demo runs flawlessly and was easy to set up. Been looking through the code for the past few hours and can't seem to figure this out. Is it possible to change the audio levels or volume for different participants in the call? By this I don't mean muting them completely, but rather changing the audio to x 0.2 or 0.6 instead of 1. Thanks!

**Comment by stasel** [comment]
Hey @marvinkennis 
Sorry for the late response. I haven't tried it but since WebRTC a `AVaudiosession` for recording the audio, you can try to check the documentation there as a starting point

**Comment by stasel** [comment]
Hi, this issue has been closed due to inactivity. Please feel free to reopen it if you still experiencing issues.
