### ISSUE TITLE
1 to many?

### ISSUE THREAD

**Issue by sashastg** [stasel/WebRTC-iOS#48]
Hello,
is it possible to use this library to share 1 video to few devices?
for example:  1 device is broadcasting  and  2 devices watch on video from 1 device?

if its possible, can you provide some example?

**Comment by stasel** [comment]
Hey @sashastg 
WebRTC library is build around 1 to 1 connection. However, you can have 1 to many with WebRTC. This unfortunately is not covered in this example project but you can google 'webrtc MCU' to get more information
