### ISSUE TITLE
Cannot create connection with different network

### ISSUE THREAD

**Issue by tungngodinh** [stasel/WebRTC-iOS#49]
Hi stasel.
Thank for great example.
It worked successfully when in a wifi.
But when different network RTCIceConnectionStateFailed.
I tried to use my TURN server replace Google STUN server but I still getting the same error.
I hope to receive help.
Thank

**Comment by sashastg** [comment]
1) in same network its must works without any stun/turns servers.  you need only your signaling server.
2) if point #1  works for you and you have problems only in different networks, its means that you need use TURN server.
i used myself  coturn server.
for check it turn server is working you can use:
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Comment by stasel** [comment]
Hey,
The example should work properly with correct TURN servers deployed. I would make sure that everything is configured correctly and the firewalls allow to establish connection between TURN server and both of the clients

**Comment by tungngodinh** [comment]
> 1. in same network its must works without any stun/turns servers.  you need only your signaling server.
> 2. if point #1  works for you and you have problems only in different networks, its means that you need use TURN server.
>    i used myself  coturn server.
>    for check it turn server is working you can use:
>    https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/



> Hey,
> The example should work properly with correct TURN servers deployed. I would make sure that everything is configured correctly and the firewalls allow to establish connection between TURN server and both of the clients

Thanks for helping me, I will check the TURN server

**Comment by stasel** [comment]
Hi, this issue has been closed due to inactivity. Please feel free to reopen it if you still experiencing issues.
