### ISSUE TITLE
Consumes more battery on iPhone

### ISSUE THREAD

**Issue by mohitgorakhiya** [stasel/WebRTC-iOS#50]
I am using WebRTC framework for Video Call feature, it works proper but have issue of battery draining much fast in iPhone.
In 9 mins of call it drains around 30% the battery.

So any idea what is the issue here?

**Comment by yspreen** [comment]
More battery than what

**Comment by mohitgorakhiya** [comment]
I mean battery drain fast.
In 9 mins of video call it drains around 30% the battery.

**Comment by stasel** [comment]
Hi @mohitgorakhiya ,
It is known that in general, Video streaming has a large impact on the device's battery life. The WebRTC library is no different and indeed takes a significant amount of battery. 
I would first test your phone's battery condition to see if maybe the battery is not in it's maximum capacity (specially for phones older than 2- 3 years).

**Comment by mohitgorakhiya** [comment]
Hi stasel
I have iPhone 6s with me and it has battery life 85%

**Comment by stasel** [comment]
Can you maybe try to reduce the frame rate and/or the resolution in [WebRTCClient.swift](https://github.com/stasel/WebRTC-iOS/blob/master/WebRTC-Demo-App/Sources/Services/WebRTCClient.swift#L104) and check again if you have less batter impact?

**Comment by stasel** [comment]
Hi, this issue has been closed due to inactivity. Please feel free to reopen it if you still experiencing issues.
