### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by jdominiak** [stasel/WebRTC-iOS#57]
Is it possible to connect with multiple users on video chat?

**Comment by sanamsta** [comment]
Yes you have to create multiple peerconnection object for each client...

**Comment by stasel** [comment]
Unfortunately, in this demo app, I have implemented only one to one calls. Group calls are out of the scope for this demo.
Group call has several different implementation methods, I suggest watching the  [Intro to WebRTC](https://www.youtube.com/watch?v=p2HzZkd2A40) video where it is briefly explained.
