### ISSUE TITLE
Connection Failed - "Bad address" ( iOS14 )

### ISSUE THREAD

**Issue by drunknbass** [stasel/WebRTC-iOS#59]
When attempting to establish a p2p connection an error is received. 
2020-07-03 20:08:28.841589-0700 SignalingServer[88784:786666] [connection] nw_read_request_report [C1] Receive failed with error "Bad address"

This is unique to iOS14. Any idea?

**Comment by stasel** [comment]
Hey, thanks for reporting. I plan to start testing iOS 14 and xcode-12 in the next couple of weeks. 
I do see the problem as well, something must have changed in the websocket client.

Try to use the 3rd party library Starscrean by modifying `buildSignalingClient()` function inside  `AppDelegate.swift`

**Comment by stasel** [comment]
Hi, it looks like on iOS 14.0 release version I have no longer issues with the socket connection. 
I'm closing this issue. Feel free to reopen it if you still have any issues
