### ISSUE TITLE
is it possible disable generate video in sdp?

### ISSUE THREAD

**Issue by bmp123** [stasel/WebRTC-iOS#61]
I don't need video tags in sdp! How can I disable video?
private let mediaConstrains = [kRTCMediaConstraintsOfferToReceiveAudio: kRTCMediaConstraintsValueTrue,
                                   kRTCMediaConstraintsOfferToReceiveVideo: kRTCMediaConstraintsValueFalse]

**Comment by stasel** [comment]
Yes, you are correct. if you set `kRTCMediaConstraintsOfferToReceiveVideo` to false, your SDP shouldn't contain video details. 
To check yourself, run a test with two SDPs, one with video enabled and one with disable and compare between those two

**Comment by bmp123** [comment]
Thank you for your quiсk answer. But I set this flag and in generated sdp I see m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127
It's not work for me... What I forget?

**Comment by stasel** [comment]
Hey, I think I found the reason. Because the demo app always creates a video channel, then we get all video details in the SDP. So what you can do is to comment out the video channel creation in `createMediaSenders` method in `WebRTCClient.swift` and it will generate a shorter version of SDP

**Comment by stasel** [comment]
Hi, this issue has been closed due to inactivity. Please feel free to reopen it if you are still experiencing issues.
