### ISSUE TITLE
toggle video track

### ISSUE THREAD

**Issue by sashastg** [stasel/WebRTC-iOS#62]
Hello,
i am trying to toggle  video track inside webrtc connection.
and i found bug:

if i use:
config.sdpSemantics = .unifiedPlan
self.videoSender = peerConnection.add(videoTrack, streamIds: ["stream0"])

and after i do:
peerConnection.removeTrack(self.videoSender)

video freezes, audio still works - and this is fine for this step.

After i want give back video track to connection.
and i do:
self.videoSender = peerConnection.add(videoTrack, streamIds: ["stream0"])

but video not goes.

BUT   if i use  
config.sdpSemantics = .planB
self.stream = WebRTCClient.factory.mediaStream(withStreamId: "stream");
self.stream?.addAudioTrack(self.audioTrack!);
self.stream?.addVideoTrack(self.localVideoTrack!);
self.peerConnection.add(self.stream!)

self.stream?.removeVideoTrack(self.localVideoTrack!);  -- video removes
self.stream?.addVideoTrack(self.localVideoTrack!)  -- video appear. all ok! great!
BUT
i dont know how to get remoteVideoTrack
self.peerConnection.transceivers  works only for . unifiedPlan

any ideas?

**Comment by stasel** [comment]
Hi, Apologies for the late response.
Maybe a better option is to enable/disable the video track instead of adding/removing it.
Someone was kind enough to add this functionality recently in this [PR](https://github.com/stasel/WebRTC-iOS/pull/66)
Try to pull latest code and try using `hideVideo` and `showVideo` functions

**Comment by stasel** [comment]
Hi, this issue has been closed due to inactivity. Please feel free to reopen it if you are still experiencing issues.
