### ISSUE TITLE
Multi peer connection

### ISSUE THREAD

**Issue by sanamsta** [stasel/WebRTC-iOS#63]
I have created multiple peer connection for each client and when new user connect to server it sends offer to others client and they will send answer to offer client... This works for two user but when third user  try to join other two it stuck on checking..any guide for multi peer connection

**Comment by lygon55555** [comment]
@sanamsta Hi. Is multi peer connection working?
I study WebRTC on iOS these days. I'm so curious about multi peer connection.

**Comment by sanamsta** [comment]
Yes multi peer connection is working fine.

**Comment by lygon55555** [comment]
@sanamsta If you are okay, can I check your code?
It'd be an honor if you help me 🙌

**Comment by sanamsta** [comment]
Sorry but i cant share the code but i can give you idea. You have to create your own signaling server to handle multiple users. when new user connect to the server create peer-connection in client side accordingly. Here is the link from where i got the idea.. https://github.com/kolson25/WebRTC-Multi-Peer-Video-Audio . https://www.tutorialspoint.com/webrtc/webrtc_signaling.htm

**Comment by lygon55555** [comment]
@sanamsta Thank you for your advice!

**Comment by Abhishek-Verma1** [comment]
@sanamsta @lygon55555 @stasel 
 I am working on iOS WebRTC mesh conference call of 4 persons and after running video conference call of 5 or 6 minutes, memory size is increasing and whole application becomes hang
For ref.
https://stackoverflow.com/questions/68068627/ios-webrtc-mesh-video-conference-call-memory-increasing-issue

Have you tried 4 person peer to peer(mesh based) video conference call and face any such issue?

**Comment by sanamsta** [comment]
@Abhishek-Verma1 use media server (kurento) to handle multiple clients

**Comment by Abhishek-Verma1** [comment]
> @Abhishek-Verma1 use media server (kurento) to handle multiple clients

I does not wants to use any media server. I am looking a solution for peer to peer mesh based conference call.

**Comment by sanamsta** [comment]
@Abhishek-Verma1 peer to peer connection require n-1 bandwidth to handle calls.There may be memory leaks in your application.

**Comment by Abhishek-Verma1** [comment]
@sanamsta Have you face any issue at your end also ?

**Comment by Abhishek-Verma1** [comment]
> @Abhishek-Verma1 peer to peer connection require n-1 bandwidth to handle calls.There may be memory leaks in your application.

Do you have any working sample for this ?
