### ISSUE TITLE
Signaling Status Not Coonected

### ISSUE THREAD

**Issue by cnfuzedRk62** [stasel/WebRTC-iOS#65]
Hi team please help me. It shows Signaling status not connected. Why this happening. I checked out the config.swift file and this is my code.

import Foundation

// Set this to the machine's address which runs the signaling server
fileprivate let defaultSignalingServerUrl = URL(string: "ws://localhost:8080")!

// We use Google's public stun servers. For production apps you should deploy your own stun/turn servers.
fileprivate let defaultIceServers = ["stun:stun.l.google.com:19302",
                                     "stun:stun1.l.google.com:19302",
                                     "stun:stun2.l.google.com:19302",
                                     "stun:stun3.l.google.com:19302",
                                     "stun:stun4.l.google.com:19302"]

struct Config {
    let signalingServerUrl: URL
    let webRTCIceServers: [String]
    
    static let `default` = Config(signalingServerUrl: defaultSignalingServerUrl, webRTCIceServers: defaultIceServers)
}

**Comment by stasel** [comment]
Hi, Did you start the signaling server?
Also, in your config you are using localhost as the websocket server which means only simulators will be able to connect to the signaling server.

**Comment by stasel** [comment]
Hi, this issue has been closed due to inactivity. Please feel free to reopen it if you are still experiencing issues.

**Comment by KalpeshBiniykiya** [comment]
i am getting error while connecting signaling server 
"Trying to reconnect to signaling server..."
