### ISSUE TITLE
Speaker output

### ISSUE THREAD

**Issue by decanus** [stasel/WebRTC-iOS#67]
So I am trying to get the loud speaker output if the headphones are not connected automatically and otherwise use headphones. The `speaker` button overrides this in general. Do you know how to do this.

I've already tried using `[.defaultToSpeaker]` options to see if it would work but this then again uses the receiver speaker instead of the main.

**Comment by decanus** [comment]
Figured out the issue, it seems like it depends on when the AVAudioSession is initialized.

**Comment by artur-zaremba** [comment]
> Figured out the issue, it seems like it depends on when the AVAudioSession is initialized.

Hello, nice to hear that. Could you provide some details of what you have figured out?
