### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fbenpao** [stasel/WebRTC-iOS#68]
Showing All Messages
x-swift-package-repository-authentication://?scm=com.apple.dt.Xcode.sourcecontrol.Git&url=git@github.com:daltoniam/Starscream.git#error=-1002 Authentication failed because the credentials were rejected

**Comment by stasel** [comment]
Hey, can you to change the source to http or login to github using ssh?

**Comment by stasel** [comment]
Hey again, I have updated the code to use HTTPS for swift package manager. It should resolve the issue
