### ISSUE TITLE
Is it possible to use end2end encryption using Secure Frames?

### ISSUE THREAD

**Issue by stoneburner** [stasel/WebRTC-iOS#69]
according to this article it is already possible:
https://webrtcbydralex.com/index.php/2020/03/30/secure-frames-sframes-end-to-end-media-encryption-with-webrtc-now-in-chrome/

It looks like the interface is here:

https://webrtc.googlesource.com/src/+/refs/heads/master/api/rtp_sender_interface.h

but it seems like it is not exposed by WebRTCClient.swift

**Comment by stasel** [comment]
Hi, thanks for the suggestion.
It looks pretty advanced topic and I think it's out of the scope for this kind of demo project.
I didn't find any Objc API either and since we use Google's Objc framework we cannot access directly to the native code.
