### ISSUE TITLE
Signalling status: Not connected

### ISSUE THREAD

**Issue by srinivasuk** [stasel/WebRTC-iOS#7]
Hello,

I have installed your app, ran signalling server at port 8080, but when i launched app it says 
Signalling status: Not connected

<img width="492" alt="screen shot 2018-10-10 at 6 21 47 pm" src="https://user-images.githubusercontent.com/1000702/46771507-76443e00-ccb9-11e8-9261-ae3d8949e177.png">

thanks,
-Kota

**Comment by srinivasuk** [comment]
my bad i resolved it..ip address is hardcoded in the SignalClient.swift, they should have kept localhost or 127.0.0.1 instead of hardcoding 192 address. They mentioned in the README file to change ip address to public ip address though

**Comment by stasel** [comment]
Thanks for the input!, I am working to improve that and include some sort of config file so people can just configure everything in once place instead of going through the code and changing it

**Comment by Seemapadiya** [comment]
@srinivasuk Same issues occurs, can you please guide me to resolve this issues

**Comment by aravindiOSdev** [comment]
if i change i get crash error 

fileprivate let defaultSignalingServerUrl = URL(string: "localhost:8080")!

* Terminating app due to uncaught exception 'NSGenericException', reason: 'WebSocket tasks can only be created with ws or wss schemes'

if i do like this it not connected 

fileprivate let defaultSignalingServerUrl = URL(string: "wss://localhost:8080/")!

<1> HTTP load failed, 0/0 bytes (error code: -1004 [1:61])
"Trying to reconnect to signaling server..."


thank you ..

**Comment by stasel** [comment]
If you run WebSocket server without TLS your url should be `ws://localhost:8080`

**Comment by aravindiOSdev** [comment]
@stasel thank you for replay 

i had changed 

fileprivate let defaultSignalingServerUrl = URL(string: "ws://localhost:8080")! 

not connect its show some error like this 

2020-01-02 10:49:38.102625+0530 WebRTC-Demo[397:37936] [] nw_socket_handle_socket_event [C1.2:2] Socket SO_ERROR [61: Connection refused]
2020-01-02 10:49:38.103022+0530 WebRTC-Demo[397:37936] Connection 1: received failure notification
2020-01-02 10:49:38.103071+0530 WebRTC-Demo[397:37936] Connection 1: failed to connect 1:61, reason -1
2020-01-02 10:49:38.103272+0530 WebRTC-Demo[397:37936] Connection 1: encountered error(1:61)
2020-01-02 10:49:38.105059+0530 WebRTC-Demo[397:37936] Task <CDEDC9BB-831A-41CD-A15E-82B05A037B4A>.<1> HTTP load failed, 0/0 bytes (error code: -1004 [1:61])
"Trying to reconnect to signaling server..."

**Comment by aravindiOSdev** [comment]
thank you its working 

did we can make group video call in this ?????
