### ISSUE TITLE
Sometimes setRemoteDescription just hangs

### ISSUE THREAD

**Issue by stoneburner** [stasel/WebRTC-iOS#70]
In almost all cases everything works, but sometimes the call to `setRemoteDescription` does not return (or call the completion handler)

I added logging to check for that:

    func set(remoteSdp: RTCSessionDescription, completion: @escaping (Error?) -> Void) {
        log.info("setting sdp 1")
        self.peerConnection.setRemoteDescription(remoteSdp, completionHandler: completion)
        log.info("setting sdp 2")
    }

In the case of connection failure, "setting sdp 2" never appears in the log.

I use the current cocoapod version of the webrtc library.

I will try to compile it from the official sources to check if that helps.

Edit: it did not help

**Comment by stasel** [comment]
Thanks for reporting. That is very strange that the second log doesn't happen. It should be on the same thread and according to the API, it looks like `setRemoteDescription` method is async so I wonder what is the case here.

BTW, the pod lib in this project is the official distribution by Google.

Can you somehow narrow down to the scenarios when this happens?

**Comment by stoneburner** [comment]
i figured it out, it was my fault...

i added the ability to "Hangup" the call by calling `peerConnection.close()` - which worked, but sometimes subsequent calls get stuck

.... what is the recommended way to end a call btw?

**Comment by stasel** [comment]
I'm glad that it got sorted out. With my experience, `peerConnection.close()` is enough to terminate the connection, you can also release the `peerConnection` because you need to create a new instance every call (If I recall correctly)
