### ISSUE TITLE
Not able to connect to WebSocket.

### ISSUE THREAD

**Issue by sjr30** [stasel/WebRTC-iOS#72]
Getting this error: HTTP load failed. Tried allow arbitrary loads: Yes in info.plist, still it's not working. Any suggestions?

**Comment by stasel** [comment]
Hey, make sure:
1. The signaling server is running
2. The IP of the signaling server is set correctly in `config.swift` file. `127.0.0.1` will not work if you run the code on a device, you need to use a reachable host in the network
3. If you use iOS 14, make sure to accept the permission to access local networks

**Comment by sjr30** [comment]
My firewall was preventing, got it. Thanks!

**Comment by stasel** [comment]
Good to know 👍
