### ISSUE TITLE
Socket IO Not supported WebRTC-iOS 

### ISSUE THREAD

**Issue by KalpeshBiniykiya** [stasel/WebRTC-iOS#76]
I am try to connect my SocketIO its given error!

Can you please make Support this Demo SocketIO

**Comment by KalpeshBiniykiya** [comment]
I am getting below type of error 

 **Task <CA8BEA98-9787-4F75-A7E4-C26C49934A43>.<1> HTTP load failed, 668/0 bytes (error code: -1005 [4:-4])**

****"Trying to reconnect to signaling server..."****

**Comment by stasel** [comment]
Hi, Apologies for the late response. 
Unfortunately I do not support different signaling servers and I don't have plans to add them in the future.

The purpose of this demo app is to help other developers to understand how to use WebRTC so they can do those kind of changes themselves.

Hope you understand
