### ISSUE TITLE
WebRTC-iOS to Amazon S3

### ISSUE THREAD

**Issue by SanthoshMKunthe** [stasel/WebRTC-iOS#84]
Sorry for posting this query as issue. But I would like to know is it possible to store WebRTC-iOS in S3.
If yes could you kindly provide guidance regarding the same.

**Comment by stasel** [comment]
Hi @SanthoshMKunthe 
You can use the Discussion section to ask those kind of question.
For your question, yes you can store the project in S3, you can find more info how to use S3 in [Amazon's documentation](https://docs.aws.amazon.com/s3/index.html)
