### ISSUE TITLE
"Failed to set remote answer sdp: Called in wrong state: stable"

### ISSUE THREAD

**Issue by FarJutharat** [stasel/WebRTC-iOS#86]
Error Domain=org.webrtc.RTC_OBJC_TYPE(RTCPeerConnection) Code=-1 "Failed to set remote answer sdp: Called in wrong state: stable" UserInfo={NSLocalizedDescription=Failed to set remote answer sdp: Called in wrong state: stable}

@stasel  How to fix this issue? I need remote answer sdp.

**Comment by stasel** [comment]
Hey, I'm closing this issue because there is already a similar topic in the Discussions section
