### ISSUE TITLE
Suppose I have 3 devices then how do I select amongst which I need to share data?

### ISSUE THREAD

**Issue by anirudhamahale** [stasel/WebRTC-iOS#90]

**Comment by stasel** [comment]
Hi @anirudhamahale 
This demo project unfortunately does not support more than two devices. In order to make this functionality, you'll have to come up with your own solution and build that into your signaling server and application interface.

**Comment by anirudhamahale** [comment]
Thanks @stasel, 
If you have time can you provide link where I should look for this?
