### ISSUE TITLE
no sound after rotate device to landscape

### ISSUE THREAD

**Issue by fukemy** [stasel/WebRTC-iOS#94]
hi, i found the device suddenly lose sound when rotate device? did u meet this problem?

**Comment by stasel** [comment]
Hi @fukemy 
I tried this on the demo project and didn't experience any issues (Used iPhone X). Never heard about the problem - very strange. Are there any logs/warnings in the console?

**Comment by fukemy** [comment]
sry, it's cause by playing cell video when scrolling (setCategory ambient), i removed it. Thanks
